version: '3.0'
services:
  airflow:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - BEAM_SRC_HOME=${PWD}
      - MVN_REPO=${HOME}/.m2
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./results:/usr/local/airflow/dags/results
      - ./requirements.txt:/requirements.txt
      - /var/run/docker.sock:/var/run/docker.sock