package generators;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TestDataGenerator {

    public static List<String> generateDatasetContent() {
        return Arrays.asList(
                "code\turl\tcreator\tcreated_t\tcreated_datetime\tlast_modified_t\tlast_modified_datetime\tproduct_name\tgeneric_name\tquantity\tpackaging\tpackaging_tags\tbrands\tbrands_tags\tcategories\tcategories_tags\tcategories_fr\torigins\torigins_tags\tmanufacturing_places\tmanufacturing_places_tags\tlabels\tlabels_tags\tlabels_fr\temb_codes\temb_codes_tags\tfirst_packaging_code_geo\tcities\tcities_tags\tpurchase_places\tstores\tcountries\tcountries_tags\tcountries_fr\tingredients_text\tallergens\tallergens_fr\ttraces\ttraces_tags\ttraces_fr\tserving_size\tserving_quantity\tno_nutriments\tadditives_n\tadditives\tadditives_tags\tadditives_fr\tingredients_from_palm_oil_n\tingredients_from_palm_oil\tingredients_from_palm_oil_tags\tingredients_that_may_be_from_palm_oil_n\tingredients_that_may_be_from_palm_oil\tingredients_that_may_be_from_palm_oil_tags\tnutriscore_score\tnutriscore_grade\tnova_group\tpnns_groups_1\tpnns_groups_2\tstates\tstates_tags\tstates_fr\tbrand_owner\tmain_category\tmain_category_fr\timage_url\timage_small_url\timage_ingredients_url\timage_ingredients_small_url\timage_nutrition_url\timage_nutrition_small_url\tenergy-kj_100g\tenergy-kcal_100g\tenergy_100g\tenergy-from-fat_100g\tfat_100g\tsaturated-fat_100g\tbutyric-acid_100g\tcaproic-acid_100g\tcaprylic-acid_100g\tcapric-acid_100g\tlauric-acid_100g\tmyristic-acid_100g\tpalmitic-acid_100g\tstearic-acid_100g\tarachidic-acid_100g\tbehenic-acid_100g\tlignoceric-acid_100g\tcerotic-acid_100g\tmontanic-acid_100g\tmelissic-acid_100g\tmonounsaturated-fat_100g\tpolyunsaturated-fat_100g\tomega-3-fat_100g\talpha-linolenic-acid_100g\teicosapentaenoic-acid_100g\tdocosahexaenoic-acid_100g\tomega-6-fat_100g\tlinoleic-acid_100g\tarachidonic-acid_100g\tgamma-linolenic-acid_100g\tdihomo-gamma-linolenic-acid_100g\tomega-9-fat_100g\toleic-acid_100g\telaidic-acid_100g\tgondoic-acid_100g\tmead-acid_100g\terucic-acid_100g\tnervonic-acid_100g\ttrans-fat_100g\tcholesterol_100g\tcarbohydrates_100g\tsugars_100g\tsucrose_100g\tglucose_100g\tfructose_100g\tlactose_100g\tmaltose_100g\tmaltodextrins_100g\tstarch_100g\tpolyols_100g\tfiber_100g\tsoluble-fiber_100g\tinsoluble-fiber_100g\tproteins_100g\tcasein_100g\tserum-proteins_100g\tnucleotides_100g\tsalt_100g\tsodium_100g\talcohol_100g\tvitamin-a_100g\tbeta-carotene_100g\tvitamin-d_100g\tvitamin-e_100g\tvitamin-k_100g\tvitamin-c_100g\tvitamin-b1_100g\tvitamin-b2_100g\tvitamin-pp_100g\tvitamin-b6_100g\tvitamin-b9_100g\tfolates_100g\tvitamin-b12_100g\tbiotin_100g\tpantothenic-acid_100g\tsilica_100g\tbicarbonate_100g\tpotassium_100g\tchloride_100g\tcalcium_100g\tphosphorus_100g\tiron_100g\tmagnesium_100g\tzinc_100g\tcopper_100g\tmanganese_100g\tfluoride_100g\tselenium_100g\tchromium_100g\tmolybdenum_100g\tiodine_100g\tcaffeine_100g\ttaurine_100g\tph_100g\tfruits-vegetables-nuts_100g\tfruits-vegetables-nuts-dried_100g\tfruits-vegetables-nuts-estimate_100g\tcollagen-meat-protein-ratio_100g\tcocoa_100g\tchlorophyl_100g\tcarbon-footprint_100g\tcarbon-footprint-from-meat-or-fish_100g\tnutrition-score-fr_100g\tnutrition-score-uk_100g\tglycemic-index_100g\twater-hardness_100g\tcholine_100g\tphylloquinone_100g\tbeta-glucan_100g\tinositol_100g\tcarnitine_100g\n",
                "0000000000017\thttp://world-fr.openfoodfacts.org/produit/0000000000017/vitoria-crackers\tkiliweb\t1529059080\t2018-06-15T10:38:00Z\t1561463718\t2019-06-25T11:55:18Z\tVitória crackers\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tFrance\ten:france\tFrance\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tunknown\tunknown\ten:to-be-completed, en:nutrition-facts-completed, en:ingredients-to-be-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-to-be-completed, en:categories-to-be-completed, en:brands-to-be-completed, en:packaging-to-be-completed, en:quantity-to-be-completed, en:product-name-completed, en:photos-to-be-validated, en:photos-uploaded\ten:to-be-completed,en:nutrition-facts-completed,en:ingredients-to-be-completed,en:expiration-date-to-be-completed,en:packaging-code-to-be-completed,en:characteristics-to-be-completed,en:categories-to-be-completed,en:brands-to-be-completed,en:packaging-to-be-completed,en:quantity-to-be-completed,en:product-name-completed,en:photos-to-be-validated,en:photos-uploaded\tA compléter,Informations nutritionnelles complétées,Ingrédients à compléter,Date limite à compléter,Code emballeur à compléter,Caractéristiques à compléter,Catégories à compléter,Marques à compléter,Emballage à compléter,Quantité à compléter,Nom du produit complete,Photos à valider,Photos envoyées\t\t\t\thttps://static.openfoodfacts.org/images/products/000/000/000/0017/front_fr.4.400.jpg\thttps://static.openfoodfacts.org/images/products/000/000/000/0017/front_fr.4.200.jpg\thttps://static.openfoodfacts.org/images/products/000/000/000/0017/ingredients_fr.9.400.jpg\thttps://static.openfoodfacts.org/images/products/000/000/000/0017/ingredients_fr.9.200.jpg\t\t\t\t1569\t1569\t\t7\t3.08\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t70.1\t15\t\t\t\t\t\t\t\t\t\t\t\t7.8\t\t\t\t1.4\t0.56\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n",
                "0000000000031\thttp://world-fr.openfoodfacts.org/produit/0000000000031/cacao\tisagoofy\t1539464774\t2018-10-13T21:06:14Z\t1539464817\t2018-10-13T21:06:57Z\tCacao\t\t130 g\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tFrance\ten:france\tFrance\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tunknown\tunknown\ten:to-be-completed, en:nutrition-facts-to-be-completed, en:ingredients-to-be-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-to-be-completed, en:categories-to-be-completed, en:brands-to-be-completed, en:packaging-to-be-completed, en:quantity-completed, en:product-name-completed, en:photos-to-be-validated, en:photos-uploaded\ten:to-be-completed,en:nutrition-facts-to-be-completed,en:ingredients-to-be-completed,en:expiration-date-to-be-completed,en:packaging-code-to-be-completed,en:characteristics-to-be-completed,en:categories-to-be-completed,en:brands-to-be-completed,en:packaging-to-be-completed,en:quantity-completed,en:product-name-completed,en:photos-to-be-validated,en:photos-uploaded\tA compléter,Informations nutritionnelles à compléter,Ingrédients à compléter,Date limite à compléter,Code emballeur à compléter,Caractéristiques à compléter,Catégories à compléter,Marques à compléter,Emballage à compléter,Quantité complétée,Nom du produit complete,Photos à valider,Photos envoyées\t\t\t\thttps://static.openfoodfacts.org/images/products/000/000/000/0031/front_fr.3.400.jpg\thttps://static.openfoodfacts.org/images/products/000/000/000/0031/front_fr.3.200.jpg\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n"
        );
    }

    public static Map<String, String> generateDataMap1() {
        Map<String, String> testDataMap1 = new HashMap<>();
        testDataMap1.put("code", "0000000000017");
        testDataMap1.put("url", "http://world-fr.openfoodfacts.org/produit/0000000000017/vitoria-crackers");
        testDataMap1.put("creator", "kiliweb");
        testDataMap1.put("created_t", "1529059080");
        testDataMap1.put("created_datetime", "2018-06-15T10:38:00Z");
        testDataMap1.put("last_modified_t", "1561463718");
        testDataMap1.put("last_modified_datetime", "2019-06-25T11:55:18Z");
        testDataMap1.put("product_name", "Vitória crackers");
        testDataMap1.put("generic_name", "");
        testDataMap1.put("quantity", "");
        testDataMap1.put("packaging", "");
        testDataMap1.put("packaging_tags", "");
        testDataMap1.put("brands", "");
        testDataMap1.put("brands_tags", "");
        testDataMap1.put("categories", "");
        testDataMap1.put("categories_tags", "");
        testDataMap1.put("categories_fr", "");
        testDataMap1.put("origins", "");
        testDataMap1.put("origins_tags", "");
        testDataMap1.put("manufacturing_places", "");
        testDataMap1.put("manufacturing_places_tags", "");
        testDataMap1.put("labels", "");
        testDataMap1.put("labels_tags", "");
        testDataMap1.put("labels_fr", "");
        testDataMap1.put("emb_codes", "");
        testDataMap1.put("emb_codes_tags", "");
        testDataMap1.put("first_packaging_code_geo", "");
        testDataMap1.put("cities", "");
        testDataMap1.put("cities_tags", "");
        testDataMap1.put("purchase_places", "");
        testDataMap1.put("stores", "");
        testDataMap1.put("countries", "France");
        testDataMap1.put("countries_tags", "en:france");
        testDataMap1.put("countries_fr", "France");
        testDataMap1.put("ingredients_text", "");
        testDataMap1.put("allergens", "");
        testDataMap1.put("allergens_fr", "");
        testDataMap1.put("traces", "");
        testDataMap1.put("traces_tags", "");
        testDataMap1.put("traces_fr", "");
        testDataMap1.put("serving_size", "");
        testDataMap1.put("serving_quantity", "");
        testDataMap1.put("no_nutriments", "");
        testDataMap1.put("additives_n", "");
        testDataMap1.put("additives", "");
        testDataMap1.put("additives_tags", "");
        testDataMap1.put("additives_fr", "");
        testDataMap1.put("ingredients_from_palm_oil_n", "");
        testDataMap1.put("ingredients_from_palm_oil", "");
        testDataMap1.put("ingredients_from_palm_oil_tags", "");
        testDataMap1.put("ingredients_that_may_be_from_palm_oil_n", "");
        testDataMap1.put("ingredients_that_may_be_from_palm_oil", "");
        testDataMap1.put("ingredients_that_may_be_from_palm_oil_tags", "");
        testDataMap1.put("nutriscore_score", "");
        testDataMap1.put("nutriscore_grade", "");
        testDataMap1.put("nova_group", "");
        testDataMap1.put("pnns_groups_1", "unknown");
        testDataMap1.put("pnns_groups_2", "unknown");
        testDataMap1.put("states", "en:to-be-completed, en:nutrition-facts-completed, en:ingredients-to-be-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-to-be-completed, en:categories-to-be-completed, en:brands-to-be-completed, en:packaging-to-be-completed, en:quantity-to-be-completed, en:product-name-completed, en:photos-to-be-validated, en:photos-uploaded");
        testDataMap1.put("states_tags", "en:to-be-completed,en:nutrition-facts-completed,en:ingredients-to-be-completed,en:expiration-date-to-be-completed,en:packaging-code-to-be-completed,en:characteristics-to-be-completed,en:categories-to-be-completed,en:brands-to-be-completed,en:packaging-to-be-completed,en:quantity-to-be-completed,en:product-name-completed,en:photos-to-be-validated,en:photos-uploaded");
        testDataMap1.put("states_fr", "A compléter,Informations nutritionnelles complétées,Ingrédients à compléter,Date limite à compléter,Code emballeur à compléter,Caractéristiques à compléter,Catégories à compléter,Marques à compléter,Emballage à compléter,Quantité à compléter,Nom du produit complete,Photos à valider,Photos envoyées");
        testDataMap1.put("brand_owner", "");
        testDataMap1.put("main_category", "");
        testDataMap1.put("main_category_fr", "");
        testDataMap1.put("image_url", "https://static.openfoodfacts.org/images/products/000/000/000/0017/front_fr.4.400.jpg");
        testDataMap1.put("image_small_url", "https://static.openfoodfacts.org/images/products/000/000/000/0017/front_fr.4.200.jpg");
        testDataMap1.put("image_ingredients_url", "https://static.openfoodfacts.org/images/products/000/000/000/0017/ingredients_fr.9.400.jpg");
        testDataMap1.put("image_ingredients_small_url", "https://static.openfoodfacts.org/images/products/000/000/000/0017/ingredients_fr.9.200.jpg");
        testDataMap1.put("image_nutrition_url", "");
        testDataMap1.put("image_nutrition_small_url", "");
        testDataMap1.put("energy-kj_100g", "");
        testDataMap1.put("energy-kcal_100g", "1569");
        testDataMap1.put("energy_100g", "1569");
        testDataMap1.put("energy-from-fat_100g", "");
        testDataMap1.put("fat_100g", "7");
        testDataMap1.put("saturated-fat_100g", "3.08");
        testDataMap1.put("butyric-acid_100g", "");
        testDataMap1.put("caproic-acid_100g", "");
        testDataMap1.put("caprylic-acid_100g", "");
        testDataMap1.put("capric-acid_100g", "");
        testDataMap1.put("lauric-acid_100g", "");
        testDataMap1.put("myristic-acid_100g", "");
        testDataMap1.put("palmitic-acid_100g", "");
        testDataMap1.put("stearic-acid_100g", "");
        testDataMap1.put("arachidic-acid_100g", "");
        testDataMap1.put("behenic-acid_100g", "");
        testDataMap1.put("lignoceric-acid_100g", "");
        testDataMap1.put("cerotic-acid_100g", "");
        testDataMap1.put("montanic-acid_100g", "");
        testDataMap1.put("melissic-acid_100g", "");
        testDataMap1.put("monounsaturated-fat_100g", "");
        testDataMap1.put("polyunsaturated-fat_100g", "");
        testDataMap1.put("omega-3-fat_100g", "");
        testDataMap1.put("alpha-linolenic-acid_100g", "");
        testDataMap1.put("eicosapentaenoic-acid_100g", "");
        testDataMap1.put("docosahexaenoic-acid_100g", "");
        testDataMap1.put("omega-6-fat_100g", "");
        testDataMap1.put("linoleic-acid_100g", "");
        testDataMap1.put("arachidonic-acid_100g", "");
        testDataMap1.put("gamma-linolenic-acid_100g", "");
        testDataMap1.put("dihomo-gamma-linolenic-acid_100g", "");
        testDataMap1.put("omega-9-fat_100g", "");
        testDataMap1.put("oleic-acid_100g", "");
        testDataMap1.put("elaidic-acid_100g", "");
        testDataMap1.put("gondoic-acid_100g", "");
        testDataMap1.put("mead-acid_100g", "");
        testDataMap1.put("erucic-acid_100g", "");
        testDataMap1.put("nervonic-acid_100g", "");
        testDataMap1.put("trans-fat_100g", "");
        testDataMap1.put("cholesterol_100g", "");
        testDataMap1.put("carbohydrates_100g", "70.1");
        testDataMap1.put("sugars_100g", "15");
        testDataMap1.put("sucrose_100g", "");
        testDataMap1.put("glucose_100g", "");
        testDataMap1.put("fructose_100g", "");
        testDataMap1.put("lactose_100g", "");
        testDataMap1.put("maltose_100g", "");
        testDataMap1.put("maltodextrins_100g", "");
        testDataMap1.put("starch_100g", "");
        testDataMap1.put("polyols_100g", "");
        testDataMap1.put("fiber_100g", "");
        testDataMap1.put("soluble-fiber_100g", "");
        testDataMap1.put("insoluble-fiber_100g", "");
        testDataMap1.put("proteins_100g", "7.8");
        testDataMap1.put("casein_100g", "");
        testDataMap1.put("serum-proteins_100g", "");
        testDataMap1.put("nucleotides_100g", "");
        testDataMap1.put("salt_100g", "1.4");
        testDataMap1.put("sodium_100g", "0.56");
        testDataMap1.put("alcohol_100g", "");
        testDataMap1.put("vitamin-a_100g", "");
        testDataMap1.put("beta-carotene_100g", "");
        testDataMap1.put("vitamin-d_100g", "");
        testDataMap1.put("vitamin-e_100g", "");
        testDataMap1.put("vitamin-k_100g", "");
        testDataMap1.put("vitamin-c_100g", "");
        testDataMap1.put("vitamin-b1_100g", "");
        testDataMap1.put("vitamin-b2_100g", "");
        testDataMap1.put("vitamin-pp_100g", "");
        testDataMap1.put("vitamin-b6_100g", "");
        testDataMap1.put("vitamin-b9_100g", "");
        testDataMap1.put("folates_100g", "");
        testDataMap1.put("vitamin-b12_100g", "");
        testDataMap1.put("biotin_100g", "");
        testDataMap1.put("pantothenic-acid_100g", "");
        testDataMap1.put("silica_100g", "");
        testDataMap1.put("bicarbonate_100g", "");
        testDataMap1.put("potassium_100g", "");
        testDataMap1.put("chloride_100g", "");
        testDataMap1.put("calcium_100g", "");
        testDataMap1.put("phosphorus_100g", "");
        testDataMap1.put("iron_100g", "");
        testDataMap1.put("magnesium_100g", "");
        testDataMap1.put("zinc_100g", "");
        testDataMap1.put("copper_100g", "");
        testDataMap1.put("manganese_100g", "");
        testDataMap1.put("fluoride_100g", "");
        testDataMap1.put("selenium_100g", "");
        testDataMap1.put("chromium_100g", "");
        testDataMap1.put("molybdenum_100g", "");
        testDataMap1.put("iodine_100g", "");
        testDataMap1.put("caffeine_100g", "");
        testDataMap1.put("taurine_100g", "");
        testDataMap1.put("ph_100g", "");
        testDataMap1.put("fruits-vegetables-nuts_100g", "");
        testDataMap1.put("fruits-vegetables-nuts-dried_100g", "");
        testDataMap1.put("fruits-vegetables-nuts-estimate_100g", "");
        testDataMap1.put("collagen-meat-protein-ratio_100g", "");
        testDataMap1.put("cocoa_100g", "");
        testDataMap1.put("chlorophyl_100g", "");
        testDataMap1.put("carbon-footprint_100g", "");
        testDataMap1.put("carbon-footprint-from-meat-or-fish_100g", "");
        testDataMap1.put("nutrition-score-fr_100g", "");
        testDataMap1.put("nutrition-score-uk_100g", "");
        testDataMap1.put("glycemic-index_100g", "");
        testDataMap1.put("water-hardness_100g", "");
        testDataMap1.put("choline_100g", "");
        testDataMap1.put("phylloquinone_100g", "");
        testDataMap1.put("beta-glucan_100g", "");
        testDataMap1.put("inositol_100g", "");
        testDataMap1.put("carnitine_100g", "");
        return testDataMap1;
    }

    public static Map<String, String> generateDataMap2() {
        Map<String, String> testDataMap2 = new HashMap<>();
        testDataMap2.put("code","0000000000031");
        testDataMap2.put("url","http://world-fr.openfoodfacts.org/produit/0000000000031/cacao");
        testDataMap2.put("creator","isagoofy");
        testDataMap2.put("created_t","1539464774");
        testDataMap2.put("created_datetime","2018-10-13T21:06:14Z");
        testDataMap2.put("last_modified_t","1539464817");
        testDataMap2.put("last_modified_datetime","2018-10-13T21:06:57Z");
        testDataMap2.put("product_name","Cacao");
        testDataMap2.put("generic_name","");
        testDataMap2.put("quantity","130 g");
        testDataMap2.put("packaging","");
        testDataMap2.put("packaging_tags","");
        testDataMap2.put("brands","");
        testDataMap2.put("brands_tags","");
        testDataMap2.put("categories","");
        testDataMap2.put("categories_tags","");
        testDataMap2.put("categories_fr","");
        testDataMap2.put("origins","");
        testDataMap2.put("origins_tags","");
        testDataMap2.put("manufacturing_places","");
        testDataMap2.put("manufacturing_places_tags","");
        testDataMap2.put("labels","");
        testDataMap2.put("labels_tags","");
        testDataMap2.put("labels_fr","");
        testDataMap2.put("emb_codes","");
        testDataMap2.put("emb_codes_tags","");
        testDataMap2.put("first_packaging_code_geo","");
        testDataMap2.put("cities","");
        testDataMap2.put("cities_tags","");
        testDataMap2.put("purchase_places","");
        testDataMap2.put("stores","");
        testDataMap2.put("countries","France");
        testDataMap2.put("countries_tags","en:france");
        testDataMap2.put("countries_fr","France");
        testDataMap2.put("ingredients_text","");
        testDataMap2.put("allergens","");
        testDataMap2.put("allergens_fr","");
        testDataMap2.put("traces","");
        testDataMap2.put("traces_tags","");
        testDataMap2.put("traces_fr","");
        testDataMap2.put("serving_size","");
        testDataMap2.put("serving_quantity","");
        testDataMap2.put("no_nutriments","");
        testDataMap2.put("additives_n","");
        testDataMap2.put("additives","");
        testDataMap2.put("additives_tags","");
        testDataMap2.put("additives_fr","");
        testDataMap2.put("ingredients_from_palm_oil_n","");
        testDataMap2.put("ingredients_from_palm_oil","");
        testDataMap2.put("ingredients_from_palm_oil_tags","");
        testDataMap2.put("ingredients_that_may_be_from_palm_oil_n","");
        testDataMap2.put("ingredients_that_may_be_from_palm_oil","");
        testDataMap2.put("ingredients_that_may_be_from_palm_oil_tags","");
        testDataMap2.put("nutriscore_score","");
        testDataMap2.put("nutriscore_grade","");
        testDataMap2.put("nova_group","");
        testDataMap2.put("pnns_groups_1","unknown");
        testDataMap2.put("pnns_groups_2","unknown");
        testDataMap2.put("states","en:to-be-completed, en:nutrition-facts-to-be-completed, en:ingredients-to-be-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-to-be-completed, en:categories-to-be-completed, en:brands-to-be-completed, en:packaging-to-be-completed, en:quantity-completed, en:product-name-completed, en:photos-to-be-validated, en:photos-uploaded");
        testDataMap2.put("states_tags","en:to-be-completed,en:nutrition-facts-to-be-completed,en:ingredients-to-be-completed,en:expiration-date-to-be-completed,en:packaging-code-to-be-completed,en:characteristics-to-be-completed,en:categories-to-be-completed,en:brands-to-be-completed,en:packaging-to-be-completed,en:quantity-completed,en:product-name-completed,en:photos-to-be-validated,en:photos-uploaded");
        testDataMap2.put("states_fr","A compléter,Informations nutritionnelles à compléter,Ingrédients à compléter,Date limite à compléter,Code emballeur à compléter,Caractéristiques à compléter,Catégories à compléter,Marques à compléter,Emballage à compléter,Quantité complétée,Nom du produit complete,Photos à valider,Photos envoyées");
        testDataMap2.put("brand_owner","");
        testDataMap2.put("main_category","");
        testDataMap2.put("main_category_fr","");
        testDataMap2.put("image_url","https://static.openfoodfacts.org/images/products/000/000/000/0031/front_fr.3.400.jpg");
        testDataMap2.put("image_small_url","https://static.openfoodfacts.org/images/products/000/000/000/0031/front_fr.3.200.jpg");
        testDataMap2.put("image_ingredients_url","");
        testDataMap2.put("image_ingredients_small_url","");
        testDataMap2.put("image_nutrition_url","");
        testDataMap2.put("image_nutrition_small_url","");
        testDataMap2.put("energy-kj_100g","");
        testDataMap2.put("energy-kcal_100g","");
        testDataMap2.put("energy_100g","");
        testDataMap2.put("energy-from-fat_100g","");
        testDataMap2.put("fat_100g","");
        testDataMap2.put("saturated-fat_100g","");
        testDataMap2.put("butyric-acid_100g","");
        testDataMap2.put("caproic-acid_100g","");
        testDataMap2.put("caprylic-acid_100g","");
        testDataMap2.put("capric-acid_100g","");
        testDataMap2.put("lauric-acid_100g","");
        testDataMap2.put("myristic-acid_100g","");
        testDataMap2.put("palmitic-acid_100g","");
        testDataMap2.put("stearic-acid_100g","");
        testDataMap2.put("arachidic-acid_100g","");
        testDataMap2.put("behenic-acid_100g","");
        testDataMap2.put("lignoceric-acid_100g","");
        testDataMap2.put("cerotic-acid_100g","");
        testDataMap2.put("montanic-acid_100g","");
        testDataMap2.put("melissic-acid_100g","");
        testDataMap2.put("monounsaturated-fat_100g","");
        testDataMap2.put("polyunsaturated-fat_100g","");
        testDataMap2.put("omega-3-fat_100g","");
        testDataMap2.put("alpha-linolenic-acid_100g","");
        testDataMap2.put("eicosapentaenoic-acid_100g","");
        testDataMap2.put("docosahexaenoic-acid_100g","");
        testDataMap2.put("omega-6-fat_100g","");
        testDataMap2.put("linoleic-acid_100g","");
        testDataMap2.put("arachidonic-acid_100g","");
        testDataMap2.put("gamma-linolenic-acid_100g","");
        testDataMap2.put("dihomo-gamma-linolenic-acid_100g","");
        testDataMap2.put("omega-9-fat_100g","");
        testDataMap2.put("oleic-acid_100g","");
        testDataMap2.put("elaidic-acid_100g","");
        testDataMap2.put("gondoic-acid_100g","");
        testDataMap2.put("mead-acid_100g","");
        testDataMap2.put("erucic-acid_100g","");
        testDataMap2.put("nervonic-acid_100g","");
        testDataMap2.put("trans-fat_100g","");
        testDataMap2.put("cholesterol_100g","");
        testDataMap2.put("carbohydrates_100g","");
        testDataMap2.put("sugars_100g","");
        testDataMap2.put("sucrose_100g","");
        testDataMap2.put("glucose_100g","");
        testDataMap2.put("fructose_100g","");
        testDataMap2.put("lactose_100g","");
        testDataMap2.put("maltose_100g","");
        testDataMap2.put("maltodextrins_100g","");
        testDataMap2.put("starch_100g","");
        testDataMap2.put("polyols_100g","");
        testDataMap2.put("fiber_100g","");
        testDataMap2.put("soluble-fiber_100g","");
        testDataMap2.put("insoluble-fiber_100g","");
        testDataMap2.put("proteins_100g","");
        testDataMap2.put("casein_100g","");
        testDataMap2.put("serum-proteins_100g","");
        testDataMap2.put("nucleotides_100g","");
        testDataMap2.put("salt_100g","");
        testDataMap2.put("sodium_100g","");
        testDataMap2.put("alcohol_100g","");
        testDataMap2.put("vitamin-a_100g","");
        testDataMap2.put("beta-carotene_100g","");
        testDataMap2.put("vitamin-d_100g","");
        testDataMap2.put("vitamin-e_100g","");
        testDataMap2.put("vitamin-k_100g","");
        testDataMap2.put("vitamin-c_100g","");
        testDataMap2.put("vitamin-b1_100g","");
        testDataMap2.put("vitamin-b2_100g","");
        testDataMap2.put("vitamin-pp_100g","");
        testDataMap2.put("vitamin-b6_100g","");
        testDataMap2.put("vitamin-b9_100g","");
        testDataMap2.put("folates_100g","");
        testDataMap2.put("vitamin-b12_100g","");
        testDataMap2.put("biotin_100g","");
        testDataMap2.put("pantothenic-acid_100g","");
        testDataMap2.put("silica_100g","");
        testDataMap2.put("bicarbonate_100g","");
        testDataMap2.put("potassium_100g","");
        testDataMap2.put("chloride_100g","");
        testDataMap2.put("calcium_100g","");
        testDataMap2.put("phosphorus_100g","");
        testDataMap2.put("iron_100g","");
        testDataMap2.put("magnesium_100g","");
        testDataMap2.put("zinc_100g","");
        testDataMap2.put("copper_100g","");
        testDataMap2.put("manganese_100g","");
        testDataMap2.put("fluoride_100g","");
        testDataMap2.put("selenium_100g","");
        testDataMap2.put("chromium_100g","");
        testDataMap2.put("molybdenum_100g","");
        testDataMap2.put("iodine_100g","");
        testDataMap2.put("caffeine_100g","");
        testDataMap2.put("taurine_100g","");
        testDataMap2.put("ph_100g","");
        testDataMap2.put("fruits-vegetables-nuts_100g","");
        testDataMap2.put("fruits-vegetables-nuts-dried_100g","");
        testDataMap2.put("fruits-vegetables-nuts-estimate_100g","");
        testDataMap2.put("collagen-meat-protein-ratio_100g","");
        testDataMap2.put("cocoa_100g","");
        testDataMap2.put("chlorophyl_100g","");
        testDataMap2.put("carbon-footprint_100g","");
        testDataMap2.put("carbon-footprint-from-meat-or-fish_100g","");
        testDataMap2.put("nutrition-score-fr_100g","");
        testDataMap2.put("nutrition-score-uk_100g","");
        testDataMap2.put("glycemic-index_100g","");
        testDataMap2.put("water-hardness_100g","");
        testDataMap2.put("choline_100g","");
        testDataMap2.put("phylloquinone_100g","");
        testDataMap2.put("beta-glucan_100g","");
        testDataMap2.put("inositol_100g","");
        testDataMap2.put("carnitine_100g","");
        return testDataMap2;
    }
}
